"""
Environment Setup Script
Prompts user for Gemini API Key and configuration values, then generates .env file
"""
import os
import sys
from pathlib import Path


def setup_environment():
    """Interactive setup for environment variables"""
    print("=" * 60)
    print("Property Management Chatbot - Environment Setup")
    print("=" * 60)
    print()
    
    # Get Gemini API Key
    print("Step 1: Gemini API Key")
    print("-" * 40)
    print("Get your API key from: https://makersuite.google.com/app/apikey")
    api_key = input("Enter your Gemini API Key: ").strip()
    
    if not api_key:
        print("ERROR: API Key is required!")
        sys.exit(1)
    
    print()
    
    # Get MAX_RETRIES
    print("Step 2: Configuration")
    print("-" * 40)
    max_retries_input = input("Enter MAX_RETRIES for SQL correction (default: 3): ").strip()
    max_retries = max_retries_input if max_retries_input else "3"
    
    try:
        int(max_retries)
    except ValueError:
        print("WARNING: Invalid number, using default: 3")
        max_retries = "3"
    
    print()
    
    # Get Model Name
    model_name_input = input("Enter Gemini model name (default: gemini-2.0-flash-exp): ").strip()
    model_name = model_name_input if model_name_input else "gemini-2.0-flash-exp"
    
    print()
    
    # Create .env file
    env_path = Path(__file__).parent.parent / ".env"
    
    env_content = f"""# Property Management Chatbot - Environment Configuration
# Generated by setup_env.py

# Google Gemini API Configuration
GOOGLE_API_KEY={api_key}
GEMINI_MODEL={model_name}

# Agent Configuration
MAX_RETRIES={max_retries}

# Database Configuration
DATABASE_PATH=property_management.db

# Debug Mode (set to true for technical error details)
DEBUG_MODE=false

# Logging
LOG_LEVEL=INFO
"""
    
    try:
        with open(env_path, 'w', encoding='utf-8') as f:
            f.write(env_content)
        
        print("✓ Environment file created successfully!")
        print(f"  Location: {env_path.absolute()}")
        print()
        print("Next steps:")
        print("  1. Run: python scripts/generate_mock_db.py")
        print("  2. Run: python main.py")
        print()
        
    except Exception as e:
        print(f"ERROR: Failed to create .env file: {e}")
        sys.exit(1)


if __name__ == "__main__":
    setup_environment()
